INFO:pyaf.timing:('OPERATION_START', ('SIGNAL_TRAINING', {'Signals': ['Signal'], 'Transformations': [('Signal', 'None', '_', 'T+S+R')], 'Cores': 1}))
INFO:pyaf.timing:('OPERATION_START', ('TRAINING', {'Signal': 'Signal', 'Transformation': '_Signal'}))
/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
Traceback (most recent call last):
  File "/home/circleci/project/pyaf/ForecastEngine.py", line 25, in train
    self.mSignalDecomposition.train(iInputDS, iTime, iSignal, iHorizon, iExogenousData);
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 666, in train
    lTrainer.train(iInputDS, lSplits , self.mDateColumns, self.mSignals, self.mHorizons)
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 416, in train
    self.train_all_transformations(iInputDS, iSplits, iTime, iSignals, iHorizon);
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 512, in train_all_transformations
    res = run_transform_thread(arg)
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 380, in run_transform_thread
    arg.mSigDec.train(arg.mInputDS, arg.mSplit, arg.mTime, arg.mSignal, arg.mHorizon, arg.mTransformation, arg.mDecompositionType);
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 194, in train
    lAREstimator.estimate();
  File "/home/circleci/project/pyaf/TS/SignalDecomposition_AR.py", line 323, in estimate
    self.add_model_if_activated(cycle_residue, 'CROSTON', interm.cCroston_Model, lLags, False)
  File "/home/circleci/project/pyaf/TS/SignalDecomposition_AR.py", line 278, in add_model_if_activated
    if(self.mOptions.mActiveAutoRegressions[model_type_str + 'X'] and (self.mExogenousInfo is not None)):
KeyError: 'CROSTONX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/project/tests/croston/test_croston_fpp2_counts_example_optimize.py", line 50, in <module>
    create_model(None)
  File "/home/circleci/project/tests/croston/test_croston_fpp2_counts_example_optimize.py", line 29, in create_model
    lEngine.train(iInputDS = df_train, iTime = 'Date', iSignal = 'Signal', iHorizon = 7);
  File "/home/circleci/project/pyaf/ForecastEngine.py", line 30, in train
    raise tsutil.PyAF_Error("TRAIN_FAILED");
pyaf.TS.Utils.PyAF_Error: TRAIN_FAILED
INFO:pyaf.timing:('OPERATION_END_ELAPSED', 0.28, ('TRAINING', {'Signal': 'Signal', 'Transformation': '_Signal'}))
INFO:pyaf.timing:('OPERATION_END_ELAPSED', 0.284, ('SIGNAL_TRAINING', {'Signals': ['Signal'], 'Transformations': [('Signal', 'None', '_', 'T+S+R')], 'Cores': 1}))
