INFO:pyaf.std:START_TRAINING 'Signal'
/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/lib/python3/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/lib/python3/dist-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/lib/python3/dist-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/usr/lib/python3/dist-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
ERROR:pyaf.std:Failure when computing perf ['_Signal_ConstantTrend_residue_zeroCycle_residue_NoAR'] '_Signal_ConstantTrend_residue_zeroCycle_residue_NoAR'
GENERATING_RANDOM_DATASET Signal_40000_S_0_constant_24_None_0.1_0
TREND 0.0976270078546495 0.43037873274483895 0.20552675214328775
Traceback (most recent call last):
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/Perf.py", line 80, in compute
    return self.real_compute(signal, estimator, name);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/Perf.py", line 129, in real_compute
    self.mSignalQuantiles = self.compute_signal_quantiles(signal , estimator);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/Perf.py", line 135, in compute_signal_quantiles
    Q = int(100 // NQ)
ZeroDivisionError: integer division or modulo by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antoine/dev/python/packages/timeseries/pyaf/tests/bugs/issue_70/test_artificial_keep_all_seasonals_second.py", line 19, in <module>
    lEngine.train(df , b1.mTimeVar , b1.mSignalVar, H);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/ForecastEngine.py", line 27, in train
    raise error
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/ForecastEngine.py", line 25, in train
    self.mSignalDecomposition.train(iInputDS, iTime, iSignal, iHorizon, iExogenousData);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition.py", line 703, in train
    lTrainer.train(iInputDS, lSplits , self.mDateColumns, self.mSignals, self.mHorizons)
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition.py", line 468, in train
    self.train_all_transofrmations(iInputDS, iSplits, iTime, iSignals, iHorizon);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition.py", line 547, in train_all_transofrmations
    res = run_transform_thread(arg)
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition.py", line 431, in run_transform_thread
    arg.mSigDec.train(arg.mInputDS, arg.mSplit, arg.mTime, arg.mSignal, arg.mHorizon, arg.mTransformation);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition.py", line 233, in train
    lAREstimator.estimate();
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition_AR.py", line 365, in estimate
    self.estimate_ar_models_for_cycle(cycle_residue);
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition_AR.py", line 261, in estimate_ar_models_for_cycle
    autoreg.computePerf();
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/SignalDecomposition_AR.py", line 55, in computePerf
    self.mARForecastPerf.compute(
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/TS/Perf.py", line 85, in compute
    raise tsutil.Internal_PyAF_Error("Failure when computing perf ['" + self.mName + "'] '" + name + "'");
pyaf.TS.Utils.Internal_PyAF_Error: Failure when computing perf ['_Signal_ConstantTrend_residue_zeroCycle_residue_NoAR'] '_Signal_ConstantTrend_residue_zeroCycle_residue_NoAR'
